name: Deploy
concurrency:
  group: deploy
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: npm ci
      - run: npm i -g aws-cdk
      - run: cdk deploy --require-approval never --verbose
      - run: npm run build
      - run: aws s3 sync --delete build s3://aaronmamparo.com
#      - run: aws cloudfront create-invalidation --distribution-id fodfhdkfhdkfh --paths "/*"
