name: Deploy
concurrency:
  group: deploy
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm i -g aws-cdk
      - name: Deploy Stack
        run: |
          AWS_DEFAULT_REGION="us-east-1" \
          AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
          AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          cdk deploy --require-approval never --verbose
